---
# tasks file for myapache

- name: "Installing httpd software"
  package:
    name: httpd
    state: present
- name: "Installing php"
  package:
    name: php
    state: present
- name: "Starting and Enabling httpd service"
  service:
    name: httpd
    state: started
    enabled: yes
- name: "Copying php file"
  copy:
    src: index.php
    dest: /var/www/html/index.php
- name: "Enabling port no {{ Server_Port }} in firewall"
  firewalld:
    port: "{{ Server_Port }}/tcp"
    state: enabled
    permanent: yes
